name: IaC

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4

      - name: Pulumi Login
        run: pulumi login --access-token ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview
        run: pulumi preview --stack dev

      - name: Pulumi Up
        run: pulumi up --stack dev --yes